PROGRAM Poem(INPUT, OUTPUT);
BEGIN
  WRITE('ROSES ARE ');
  WRITELN('RED,');
  WRITE('VIOL');
  WRITE('ETS ARE');
  WRITELN(' BLUE, ');
  WRITE('OTHERS CAN PR');
  WRITELN('OGRAM,');
  WRITE('SO CAN');
  WRITELN(' YOU. ')
END.
